# Describes the docker-compose configuration for development environments.
# These settings are not secure and are not intended for production use.
# Please override this configuration when configuring a production instance.
# This config launch Flask (gunicorn) / Postgres / Adminer

version: '3.2'

services:
  db:
    image: postgres:15.4-alpine3.18
    env_file:
      - ./environments/docker.dev
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  app:
    build:
      context: .
      dockerfile: alpine.dev.Dockerfile
    image: shhh
    depends_on:
      - db
    env_file:
      - ./environments/docker.dev
    ports:
      - 8081:8081
    volumes:
      - .:/opt/shhh:delegated

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8082:8080

volumes:
  postgres:
