# Describes the docker-compose configuration for development environments.
# These settings are not secure and are not intended for production use.
# Please override this configuration when configuring a production instance.
# This config launch Flask / Postgres / Redis / Celery

version: '3.2'

services:
  db:
    image: postgres:12.2-alpine
    env_file:
      - ./dockerenv/env.dev-postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/data/postgres
    ports:
      - 5432:5432

  redis:
    image: redis:6.0-rc-alpine
    command: redis-server --requirepass redis123
    volumes:
      - redis:/data
    ports:
      - 6379:6379

  app:
    build: .
    command: gunicorn -c gunicorn.conf.py wsgi:app
    depends_on:
      - db
    env_file:
      - ./dockerenv/env.dev-shhh
    ports:
      - 5000:5000

  celeryworker:
    build: .
    command: >
      celery -A shhh.tasks.tasks worker
      --loglevel=INFO
      --pidfile=/var/run/celery/celeryworker-shhh.pid
    env_file:
      - ./dockerenv/env.dev-shhh

  celerybeat:
    build: .
    command: >
      celery -A shhh.tasks.tasks beat
      --loglevel=INFO
      --pidfile=/var/run/celery/celerybeat-shhh.pid
      --schedule=/var/run/celery/celerybeat-schedule
    env_file:
      - ./dockerenv/env.dev-shhh

  flower:
    image: mher/flower
    command: flower --broker=redis://:redis123@redis:6379 --port=8888
    ports:
      - 8888:8888

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  postgres:
  redis:
