# -*- coding: utf-8 -*-
# File     : docker-compose-flask.yml
# Authors  : Austin Schaffer <schaffer.austin.t@gmail.com
#            Matthieu Petiteau <mpetiteau.pro@gmail.com>
# Date     : 12.01.2020
# Desc     : Describes the docker-compose configuration for development environments.
#            These settings are not secure and are not intended for production use.
#            Please override this configuration when configuring a production instance.
#            This config launch Flask / MySQL / Redis / Celery

version: '3.2'

services:
  db:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: shhh
      MYSQL_USER: shhh
      MYSQL_PASSWORD: shhh123
    volumes:
      - ./mysql/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis:6.0-rc-alpine
    command: redis-server --requirepass redis123
    volumes:
      - redis:/data
    ports:
      - 6379:6379

  app:
    build: .
    command: python -m flask run --host="0.0.0.0" --port="5000"
    depends_on:
      - db
    environment:
      FLASK_ENV: dev-docker
      HOST_MYSQL: db
      DB_MYSQL: shhh
      USER_MYSQL: shhh
      PASS_MYSQL: shhh123
      REDIS_PASS: redis123
    ports:
      - 5000:5000

  celeryworker:
    build: .
    command: >
      celery -A shhh.tasks worker
      --loglevel=INFO
      --logfile=/var/log/celery/celeryworker-shhh.log
      --pidfile=/var/run/celery/celeryworker-shhh.pid
    environment:
      FLASK_ENV: dev-docker
      HOST_MYSQL: db
      DB_MYSQL: shhh
      USER_MYSQL: shhh
      PASS_MYSQL: shhh123
      REDIS_PASS: redis123

  celerybeat:
    build: .
    command: >
      celery -A shhh.tasks beat
      --loglevel=INFO
      --logfile=/var/log/celery/celerybeat-shhh.log
      --pidfile=/var/run/celery/celerybeat-shhh.pid
      --schedule=/var/run/celery/celerybeat-schedule
    environment:
      FLASK_ENV: dev-docker
      HOST_MYSQL: db
      DB_MYSQL: shhh
      USER_MYSQL: shhh
      PASS_MYSQL: shhh123
      REDIS_PASS: redis123

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  mysql_data:
  redis:
