name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements.dev.txt
    - name: Linting checks
      run: |
        # stop the build if there are any Python syntax errors
        ruff check shhh tests --exclude shhh/migrations/ --exclude
    - name: SAST analysis
      run: |
        bandit -r shhh -x shhh/static
    - name: Test suite
      run: |
        pytest --cov=shhh tests
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
